-- Seed: verified ETF universe (generated by scripts/generate-universe-seed.mjs from
-- supabase/seed-data/universe.json, verified 2026-07-23 against AMFI NAVAll +
-- Yahoo chart API). Do not hand-edit; regenerate.

insert into etfs (isin, name, yahoo_symbol, amfi_scheme_code, underlying_index,
                  asset_class, intl, ltcg_months, listed_on) values
  ('INF204KB14I2', 'Nippon India ETF Nifty 50 BeES', 'NIFTYBEES.NS', '140084', 'NIFTY 50', 'equity', false, null, '2009-01-01'),
  ('INF179KC1965', 'HDFC NIFTY 50 ETF - Growth Plan', 'HDFCNIFTY.NS', '135853', 'NIFTY 50', 'equity', false, null, '2015-12-09'),
  ('INF109K012R6', 'ICICI Prudential Nifty 50 ETF', 'NIFTYIETF.NS', '121366', 'NIFTY 50', 'equity', false, null, '2013-03-21'),
  ('INF200KA1FS1', 'SBI Nifty 50 ETF', 'SETFNIF50.NS', '135106', 'NIFTY 50', 'equity', false, null, '2015-07-23'),
  ('INF247L01DJ0', 'Motilal Oswal Nifty India Defence ETF', 'MODEFENCE.NS', '152846', 'NIFTY INDIA DEFENCE', 'equity', false, null, '2024-08-26'),
  ('INF769K01IB1', 'Mirae Asset Nifty India Manufacturing ETF', 'MAKEINDIA.NS', '149786', 'NIFTY INDIA MANUFACTURING', 'equity', false, null, '2022-01-28'),
  ('INF247L01FK3', 'Motilal Oswal Nifty India Manufacturing ETF', 'MOMGF.NS', '153572', 'NIFTY INDIA MANUFACTURING', 'equity', false, null, '2025-05-28'),
  ('INF204KC1GH6', 'Nippon India Nifty India Manufacturing ETF', 'MANUFGBEES.NS', '153810', 'NIFTY INDIA MANUFACTURING', 'equity', false, null, '2025-08-28'),
  ('INF109KC16E5', 'ICICI Prudential Nifty Infrastructure ETF', 'INFRAIETF.NS', '150526', 'NIFTY INFRASTRUCTURE', 'equity', false, null, '2022-08-18'),
  ('INF247L01FL1', 'Motilal Oswal BSE India Infrastructure ETF', 'MOINFRA.NS', '153564', 'BSE INDIA INFRASTRUCTURE', 'equity', false, null, '2025-05-21'),
  ('INF457M01133', 'CPSE ETF', 'CPSEETF.NS', '140107', 'NIFTY CPSE', 'equity', false, null, '2014-03-28'),
  ('INF109KB15Y7', 'BHARAT 22 ETF', 'ICICIB22.NS', '141957', 'BSE BHARAT 22', 'equity', false, null, '2018-07-03'),
  ('INF204KB16I7', 'Nippon India ETF Nifty PSU Bank BeES', 'PSUBNKBEES.NS', '140089', 'NIFTY PSU BANK', 'equity', false, null, '2009-01-01'),
  ('INF174KA1A86', 'Kotak Nifty PSU Bank ETF', 'PSUBANK.NS', '106929', 'NIFTY PSU BANK', 'equity', false, null, '2007-11-13'),
  ('INF209KB11D8', 'Aditya Birla Sun Life Nifty IT ETF', 'TECH.NS', '149293', 'NIFTY IT', 'equity', false, null, '2021-11-03'),
  ('INF846K01Y96', 'Axis IT ETF', 'AXISTECETF.NS', '148799', 'NIFTY IT', 'equity', false, null, '2021-03-31'),
  ('INF740KA1SX1', 'DSP Nifty IT ETF', 'ITADD.NS', '151820', 'NIFTY IT', 'equity', false, null, '2023-07-07'),
  ('INF204KB17I5', 'Nippon India ETF Gold BeES', 'GOLDBEES.NS', '140088', 'DOMESTIC GOLD', 'gold', false, null, '2009-01-01'),
  ('INF846K01W80', 'Axis Gold ETF', 'AXISGOLD.NS', '113434', 'DOMESTIC GOLD', 'gold', false, null, '2010-11-16'),
  ('INF209KB18D3', 'Aditya Birla Sun Life Gold ETF', 'BSLGOLDETF.NS', '115127', 'DOMESTIC GOLD', 'gold', false, null, '2011-05-16'),
  ('INF209KB19F6', 'Aditya Birla Sun Life Silver ETF', 'SILVER.NS', '149779', 'DOMESTIC SILVER', 'silver', false, null, '2022-01-31'),
  ('INF204KC1402', 'Nippon India Silver ETF', 'SILVERBEES.NS', '149758', 'DOMESTIC SILVER', 'silver', false, null, '2022-02-04'),
  ('INF846K016C7', 'Axis NIFTY India Consumption ETF', 'AXISCETF.NS', '149156', 'NIFTY INDIA CONSUMPTION', 'equity', false, null, '2021-09-23'),
  ('INF109KC1V42', 'ICICI Prudential Nifty India Consumption ETF', 'CONSUMIETF.NS', '149285', 'NIFTY INDIA CONSUMPTION', 'equity', false, null, '2021-10-29'),
  ('INF174KA1ZF8', 'Kotak Nifty India Consumption ETF', 'CONS.NS', '150492', 'NIFTY INDIA CONSUMPTION', 'equity', false, null, '2022-07-28'),
  ('INF666M01NI0', 'Groww Nifty Metal ETF', 'GROWWMETAL.NS', '154034', 'NIFTY METAL', 'equity', false, null, '2025-12-22'),
  ('INF109KC19W1', 'ICICI Prudential Nifty Metal ETF', 'METALIETF.NS', '152769', 'NIFTY METAL', 'equity', false, null, '2024-08-16'),
  ('INF769K01LY7', 'Mirae Asset Nifty Metal ETF', 'METAL.NS', '152924', 'NIFTY METAL', 'equity', false, null, '2024-10-04'),
  ('INF769K01PR2', 'Mirae Asset Nifty Energy ETF', 'ENERGY.NS', '153945', 'NIFTY ENERGY', 'equity', false, null, '2025-11-10'),
  ('INF247L01GH7', 'Motilal Oswal Nifty Energy ETF', 'MOENERGY.NS', '153931', 'NIFTY ENERGY', 'equity', false, null, '2025-10-16'),
  ('INF247L01AP3', 'Motilal Oswal Nasdaq 100 ETF (MOFN100)', 'MON100.NS', '114984', 'NASDAQ 100', 'intl', true, null, '2011-03-29'),
  ('INF0R8F01034', 'Zerodha Nifty 1D Rate Liquid ETF - Growth Option', 'LIQUIDCASE.NS', '152327', 'NIFTY 1D RATE', 'debt', false, null, '2024-01-17'),
  ('INF179KC1JG3', 'HDFC NIFTY 1D RATE LIQUID ETF GROWTH', 'HDFCLIQUID.NS', '153403', 'NIFTY 1D RATE', 'debt', false, null, '2023-08-31'),
  ('INF204KC1FU1', 'Nippon India Nifty 1D Rate Liquid ETF-Growth', 'LIQGRWBEES.NS', '153725', 'NIFTY 1D RATE', 'debt', false, null, '2025-07-24');

-- nav_proxy benchmark series: pinned to one verified ETF each (docs/03 §6; owner may
-- re-pin via docs/07 §13 item 13 before first ingestion)
insert into indices (name, tri_source, notes, proxy_etf_id)
select 'GOLD ETF NAV PROXY', 'nav_proxy', 'NAV series of Nippon India ETF Gold BeES', id from etfs where isin = 'INF204KB17I5';
insert into indices (name, tri_source, notes, proxy_etf_id)
select 'SILVER ETF NAV PROXY', 'nav_proxy', 'NAV series of Nippon India Silver ETF', id from etfs where isin = 'INF204KC1402';
insert into indices (name, tri_source, notes, proxy_etf_id)
select 'NASDAQ 100 NAV PROXY', 'nav_proxy', 'NAV series of Motilal Oswal Nasdaq 100 ETF (MOFN100)', id from etfs where isin = 'INF247L01AP3';
insert into indices (name, tri_source, notes, proxy_etf_id)
select 'LIQUID ETF NAV PROXY', 'nav_proxy', 'NAV series of Zerodha Nifty 1D Rate Liquid ETF - Growth Option', id from etfs where isin = 'INF0R8F01034';

insert into themes (key, name, investable, proxy_note, benchmark_index) values
  ('gold', 'Gold', true, null, 'GOLD ETF NAV PROXY'),
  ('silver', 'Silver', true, null, 'SILVER ETF NAV PROXY'),
  ('ai_global_tech', 'AI / global tech', true, 'Proxy exposure via NASDAQ 100 (intl tax + RBI-cap G6 caveats); no pure Indian AI index ETF', 'NASDAQ 100 NAV PROXY'),
  ('debt_liquid', 'Liquid / overnight debt', true, 'Exists so the conservative non-equity sleeve has a scored cohort (docs/03 §1)', 'LIQUID ETF NAV PROXY');

insert into theme_etf_map (theme_key, etf_id)
select v.theme_key, e.id from (values
  ('broad_core', 'INF204KB14I2'),
  ('broad_core', 'INF179KC1965'),
  ('broad_core', 'INF109K012R6'),
  ('broad_core', 'INF200KA1FS1'),
  ('defence', 'INF247L01DJ0'),
  ('manufacturing', 'INF769K01IB1'),
  ('manufacturing', 'INF247L01FK3'),
  ('manufacturing', 'INF204KC1GH6'),
  ('infrastructure', 'INF109KC16E5'),
  ('infrastructure', 'INF247L01FL1'),
  ('psu_value', 'INF457M01133'),
  ('psu_value', 'INF109KB15Y7'),
  ('psu_value', 'INF204KB16I7'),
  ('psu_value', 'INF174KA1A86'),
  ('it_digital', 'INF209KB11D8'),
  ('it_digital', 'INF846K01Y96'),
  ('it_digital', 'INF740KA1SX1'),
  ('gold', 'INF204KB17I5'),
  ('gold', 'INF846K01W80'),
  ('gold', 'INF209KB18D3'),
  ('silver', 'INF209KB19F6'),
  ('silver', 'INF204KC1402'),
  ('consumption', 'INF846K016C7'),
  ('consumption', 'INF109KC1V42'),
  ('consumption', 'INF174KA1ZF8'),
  ('metals_commodities', 'INF666M01NI0'),
  ('metals_commodities', 'INF109KC19W1'),
  ('metals_commodities', 'INF769K01LY7'),
  ('energy', 'INF769K01PR2'),
  ('energy', 'INF247L01GH7'),
  ('ai_global_tech', 'INF247L01AP3'),
  ('debt_liquid', 'INF0R8F01034'),
  ('debt_liquid', 'INF179KC1JG3'),
  ('debt_liquid', 'INF204KC1FU1')
) as v(theme_key, isin) join etfs e on e.isin = v.isin;

